version: '1.0'

services:
  mongoDB:
    image: mongo:latest
    container_name: mongoDB
    ports:
      - '27017:27017'

  backend:
    build: ./backend
    container_name: backend
    ports:
      - '8000:8000'
    depends_on:
      - mongoDB

  frontend:
    build: ./frontend-app
    container_name: frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
